// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-3LKyIjh4uBvZg-NQHmS3rE45Q6T6ANA',
    appId: '1:163472110583:web:aeb1c1b10d016eaa5fb4f2',
    messagingSenderId: '163472110583',
    projectId: 'to-do-app-81320',
    authDomain: 'to-do-app-81320.firebaseapp.com',
    storageBucket: 'to-do-app-81320.appspot.com',
    measurementId: 'G-FE7D77N3C9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4hASq8xk10Xg23b2Kv2l6ufYNS7Xl-28',
    appId: '1:163472110583:android:37a2f7bcc9a472575fb4f2',
    messagingSenderId: '163472110583',
    projectId: 'to-do-app-81320',
    storageBucket: 'to-do-app-81320.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM18voV-yTuXsG97ziItxpWteGt4xGnW4',
    appId: '1:163472110583:ios:0044786cff9c5a5a5fb4f2',
    messagingSenderId: '163472110583',
    projectId: 'to-do-app-81320',
    storageBucket: 'to-do-app-81320.appspot.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM18voV-yTuXsG97ziItxpWteGt4xGnW4',
    appId: '1:163472110583:ios:aa58c2f9d8454ebe5fb4f2',
    messagingSenderId: '163472110583',
    projectId: 'to-do-app-81320',
    storageBucket: 'to-do-app-81320.appspot.com',
    iosBundleId: 'com.example.toDo.RunnerTests',
  );
}
